### ISSUE TITLE
妹子你还缺男朋友吗？

### ISSUE THREAD

**Issue by travonf** [timmy3131/design-resource#4]
`echo 如题`

**Comment by timmy3131** [comment]
2333333
谁允许你开这样一个Issue了！！！

 ：）

**Comment by JakeyYe** [comment]
找啊找：）

**Comment by crayygy** [comment]
猴子观光团

**Comment by senghoo** [comment]
v2观光团到此一游。

**Comment by zhangqianrong** [comment]
V2旅游观光团到此一游

**Comment by Johnson-W** [comment]
妹纸还缺宠物吗？
单身狗一只，会暖床～求收养

**Comment by Turtur** [comment]
V2观光团到此一游

**Comment by geekwen** [comment]
V2观光团到此一游

**Comment by vicgillx** [comment]
V2观光团到此一游..哈哈哈

**Comment by dynos01** [comment]
V2观光团（滑稽）

**Comment by timmy3131** [comment]
(ーー゛)
谁能告诉我v2又发什么帖子了么。。怎么还观光团。。。

一脸懵逼.jpg

**Comment by donnol** [comment]
https://www.v2ex.com/t/300360#reply3
会不会有循环依赖。。

**Comment by x1ah** [comment]
V站观光团到此一游。

**Comment by travonf** [comment]
能和你做爱做的事吗？

**Comment by cxshun** [comment]
V2观光团到此一游

**Comment by wital** [comment]
V2观光团到此一游

**Comment by imyip** [comment]
V2观光团到此一游

**Comment by bianzhifu** [comment]
V2观光团到此一游

**Comment by GitaiQAQ** [comment]
V2观光团

**Comment by burgleaf** [comment]
v2凑热闹+1

**Comment by julypanda** [comment]
V2观光团到此一游

**Comment by ccoder64** [comment]
V2观光团到此一游

**Comment by awkj** [comment]
我一直以为Github是用来回答 [国内外有哪些比较好的同性恋交友网站？](https://www.zhihu.com/question/20056500) 的，万万没想到，这才几年啊，异性交友居然也打入 Gayhub 了。

**Comment by mdluo** [comment]
V2 guan guang tuan dao ci yi you

**Comment by time-river** [comment]
v2观光团到此一游

**Comment by wysnxzm** [comment]
V2观光团，你缺一起打游戏的朋友么

**Comment by MitaZ** [comment]
V2EX观光团到此一游
没想到你Github这浓眉大眼的家伙也叛变了，说好的最大同性交友网站呢，怎么开始做异性服务了？

**Comment by mdluo** [comment]
@MitaZ 楼主没准就是个男孩子

**Comment by timmy3131** [comment]
`不是Github叛变啊哈哈哈！
楼上那个说回答「 国内外有哪些比较好的同性恋交友网站？」的来看看，也可以回答这个呀！！
[怎样使用 GitHub？ - 珊姗是个小太阳的回答 - 知乎](https://www.zhihu.com/question/20070065/answer/79557687?group_id=749925848362000384)

⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by realpg** [comment]
V2观光团到此一游

**Comment by tracymcladdy** [comment]
观光团

**Comment by Yaoshicn** [comment]
V2观光团到此一游

**Comment by eddiexux** [comment]
V2观光团到此一游

**Comment by ghost** [comment]
V2观光团到此一游

**Comment by okchum** [comment]
V2观光团到此一游

**Comment by springhack** [comment]
V2观光团到此一游

**Comment by xfeng** [comment]
V2观光团到此一游

**Comment by dofy** [comment]
[https://v2ex.com/t/300360#reply4](https://v2ex.com/t/300360#reply4) 👈 友链

**Comment by JaminZhang** [comment]
我操 这也行？

**Comment by xwartz** [comment]
github 被玩坏了 😂

**Comment by laoertongzhi** [comment]
V2观光团到此一游

**Comment by ksco** [comment]
V2 观光团到此一游

**Comment by microchang** [comment]
v2 观光团到此一游

**Comment by admans** [comment]
V观游

**Comment by lambdaq** [comment]
V2观光团到此一游

**Comment by lambdaq** [comment]
V2观光团到此一游

**Comment by lambdaq** [comment]
V2观光团到此一游

**Comment by lambdaq** [comment]
V2观光团到此一游

**Comment by lambdaq** [comment]
V2观光团到此一游

**Comment by lambdaq** [comment]
V2观光团到此一游

**Comment by lambdaq** [comment]
V2观光团到此一游

**Comment by lambdaq** [comment]
V2观光团到此一游

**Comment by lambdaq** [comment]
V2观光团到此一游

**Comment by lambdaq** [comment]
V2观光团到此一游

**Comment by huijian222** [comment]
v2观光团到此一游

**Comment by xuecat** [comment]
世风日下、人心不古、楼上的我鄙夷你们！！！
v2观光团到此一游

**Comment by itbeihe** [comment]
V2观光团到此一游

**Comment by Graning** [comment]
v2观光团到此一游

**Comment by hoohahah** [comment]
V2观光团到此一游

**Comment by entimm** [comment]
# V2观光团到此一游

**Comment by bienyur** [comment]
V2观光团到此一游

**Comment by Arcious** [comment]
这是 github 啊～～～ v2观光

**Comment by Hanson** [comment]
V2观光团到此一游

**Comment by qbeenslee** [comment]
# V2观光团到此一游

能打广告嘛

<(￣︶￣)↗

**Comment by cfans1993** [comment]
v站电梯直达

**Comment by Ir1d** [comment]
V2观光团到此一游

**Comment by ragnraok** [comment]
V2EX观光团+1

**Comment by panxue** [comment]
V2观光团到此一游

**Comment by zhuangsirui** [comment]
V2 观光打卡

**Comment by lwjcjmx123** [comment]
v2观光打卡+1

**Comment by itanxiao** [comment]
V2 观光打卡

**Comment by hjrhclan** [comment]
V2 观观光光团  +1

**Comment by PandaraWen** [comment]
V2观光团到此一游，妹子我缺女朋友

**Comment by loveysgg** [comment]
v2观光团到此一游。

**Comment by sologgfun** [comment]
v2观光团到此一游。

**Comment by xwjdsh** [comment]
v2观光团到此一游。

**Comment by easyandroid** [comment]
v2观光团到此一游。

**Comment by LiZhenNet** [comment]
v2观光团到此一游。

**Comment by daggerjames** [comment]
V2观光团到此一游。
这波我给满分

**Comment by foodiehong** [comment]
v2观光团到此一游。

**Comment by DingSoung** [comment]
# 同问妹子有男票没😄😄

**Comment by Beerpoet** [comment]
观光

**Comment by kirafreedom** [comment]
v2观光团到此一游。

**Comment by sit-in** [comment]
v2观光团到此一游。

**Comment by sxy707** [comment]
v2观光团到此一游。

**Comment by toobit** [comment]
v2观光团到此一游。

**Comment by brunobell** [comment]
via v2ex.

**Comment by popeyelau** [comment]
`v2`观光团到此一游。

**Comment by kavnsir** [comment]
V2观光团到此一游. ^_^

**Comment by He-Pin** [comment]
@timmy3131 看了你的resume都没有看到头像，没诚意。

**Comment by lybc** [comment]
观光打卡

**Comment by Sevncz** [comment]
`'V2观光团到此一游'`

**Comment by Sevncz** [comment]
## `V2观光团到此一游`

**Comment by yangpeng7** [comment]
比V2的帖子回复还多

**Comment by Serbipunk** [comment]
v2表示：妹子你可以给他个机会试试

**Comment by ghost** [comment]
V2观光团到此一游

**Comment by xiejiangzhi** [comment]
V站观光团到此一游

**Comment by tong36** [comment]
V2观光团到此一游

**Comment by johzzy** [comment]
V2 观光团到此一游

**Comment by airzope** [comment]
V2 观光团到此一游

**Comment by channingduan** [comment]
V2观光团到此一游

**Comment by song-react** [comment]
队伍这么长了😅😅😅

**Comment by ysmoe** [comment]
v2过来的，打卡

**Comment by imricky** [comment]
V2 观光团到此一游

**Comment by luohao-lab** [comment]
V2 观光团到此一游

**Comment by dzgrief** [comment]
V2观光团到此一游

**Comment by yunhungo** [comment]
V2观光团到此一游

**Comment by autocar23** [comment]
# V2观光团

**Comment by megatontech** [comment]
同性交友请联系QQ：337845818

**Comment by CodeIdeal** [comment]
v2观光团

**Comment by cnwangjie** [comment]
V2观光团到此一游

**Comment by Inaho-yzb** [comment]
V2观光团到此一游

**Comment by vickwv** [comment]
V2强势围观

**Comment by Kiris-tingna** [comment]
妹子你还缺男朋友吗？

**Comment by iseekwonderful** [comment]
# V2观光团到此一游

**Comment by qhxin** [comment]
v2观光团到此一游

**Comment by LINAICAI** [comment]
V2观光团到此一游

**Comment by lolosssss** [comment]
v2观光团到此一游

**Comment by voidjay** [comment]
因为你的这个问题，我的手机邮箱一直哔哔毙的响

**Comment by yunhungo** [comment]
是啊  一直响个不停 :100:

**Comment by poria-cat** [comment]
特意围观~

**Comment by F-TD5X** [comment]
v2观光团到此一游

**Comment by JakeyYe** [comment]
发这么多啊，没意思：（

**Comment by chinawiz** [comment]
**# V2观光团到此一游**

**Comment by litianyou** [comment]
V2观光团到此一游

**Comment by zdzliqian** [comment]
V2观光团

**Comment by HFO4** [comment]
V2观光团到此一游

**Comment by song-react** [comment]
Gmail已经把Github通知设置垃圾邮件了， 不让总是通知，半夜也是，程序员们晚上都不睡觉的么

**Comment by Ir1d** [comment]
@DingSoung 可以改自己的设置的

**Comment by cTrloio** [comment]
V2观光团~~

**Comment by badlooop** [comment]
这个issue还没close啊

**Comment by Bin13** [comment]
V2观光团

**Comment by edisonator** [comment]
没close说明真的缺一个啊！

**Comment by DingSoung** [comment]
追女孩子  技巧也许不够，但是稍微用点心，找一下@timmy3131 的联系方式私聊应该不太难吧

**Comment by ysmoe** [comment]
看没close再来一帖

**Comment by ma3252788** [comment]
知乎观光团

**Comment by Kandychen88** [comment]
**我很想领养一只猿**

**Comment by EastHJ** [comment]
```
                                                                                  ‎想领就领喽,最重要的是行动。想只会留在脑海中                                                                                                                                                                                                                                                                                                                                        发送自我的 BlackBerry 10 智能手机。                                                                                                                                                                                                                发件人： Kandychen88已发送： 2016年9月20日星期二 15:24收件人： timmy3131/design-resource答复： timmy3131/design-resource主题： Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)我很想领养一只猿
```

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/timmy3131/design-resource","title":"timmy3131/design-resource","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/timmy3131/design-resource"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kandychen88 in #4: **我很想领养一只猿**"}],"action":{"name":"View Issue","url":"https://github.com/timmy3131/design-resource/issues/4#issuecomment-248221930"}}}

**Comment by Kiris-tingna** [comment]
不惜开小号，你也要来凑热闹。等男人上钩吗？-.-  @Kandychen88

**Comment by Kandychen88** [comment]
Hello to whom may concern,
非常感谢您的善意提醒，赶脚现实生活中无从下手哇。接触不到这类物种但是赶脚他们真的是一个神奇的生物，就是编程啊黑客啊APP哇。你这边有神马建议吗？

来自 魅族 MX

-------- 原始邮件 --------
发件人：EastHJ notifications@github.com
时间：周二 9月20日 19:26
收件人：timmy3131/design-resource design-resource@noreply.github.com
抄送：Kandychen88 18221430110@163.com,Comment comment@noreply.github.com
主题：Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)

**Comment by Kandychen88** [comment]
这个不是我的小号哇，就是正常的一个账号。
另外，也不是上钩不上钩了，辣么多人有已婚有未婚有男人有女人甚至可能有老前辈天南地北五湖四海的，如果能遇到一个心意相同的那不也是一个难得的缘分嘛？

来自 魅族 MX

-------- 原始邮件 --------
发件人：克里斯汀娜 notifications@github.com
时间：周二 9月20日 20:17
收件人：timmy3131/design-resource design-resource@noreply.github.com
抄送：Kandychen88 18221430110@163.com,Mention mention@noreply.github.com
主题：Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)

**Comment by EastHJ** [comment]
```
                                                                                  ‎这首先要看你在哪里了,其次你是想找个对的人,还是一种尝试的冲动。猿们一般都很忙,没有太多时间陪你！                                                                                                                                                                                                                                                                                                                                        发送自我的 BlackBerry 10 智能手机。                                                                                                                                                                                                                发件人： Kandychen88已发送： 2016年9月20日星期二 20:56收件人： timmy3131/design-resource答复： timmy3131/design-resource抄送： EastHJ; Comment主题： Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)Hello to whom may concern,
```

非常感谢您的善意提醒，赶脚现实生活中无从下手哇。接触不到这类物种但是赶脚他们真的是一个神奇的生物，就是编程啊黑客啊APP哇。你这边有神马建议吗？

来自 魅族 MX

-------- 原始邮件 --------
发件人：EastHJ notifications@github.com
时间：周二 9月20日 19:26
收件人：timmy3131/design-resource design-resource@noreply.github.com
抄送：Kandychen88 18221430110@163.com,Comment comment@noreply.github.com
主题：Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)

> ‎想领就领喽,最重要的是行动。想只会留在脑海中 发送自我的 BlackBerry 10 智能手机。 发件人： Kandychen88已发送： 2016年9月20日星期二 15:24收件人： timmy3131/design-resource答复： timmy3131/design-resource主题： Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)我很想领养一只猿
> 
> —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/timmy3131/design-resource","title":"timmy3131/design-resource","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/timmy3131/design-resource"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kandychen88 in #4: **我很想领养一只猿**"}],"action":{"name":"View Issue","url":"https://github.com/timmy3131/design-resource/issues/4#issuecomment-248221930"}}} 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.￼
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/timmy3131/design-resource","title":"timmy3131/design-resource","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/timmy3131/design-resource"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EastHJ in #4: ‎想领就领喽,最重要的是行动。想只会留在脑海中 发送自我的 BlackBerry 10 智能手机。 发件人： Kandychen88已发送： 2016年9月20日星期二 15:24收件人： timmy3131/design-resource答复： timmy3131/design-resource主题： Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)我很想领养一只猿\n\n—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.\n\n\n \n \n\n\n\n\n{\"api_version\":\"1.0\",\"publisher\":{\"api_key\":\"05dde50f1d1a384dd78767c55493e4bb\",\"name\":\"GitHub\"},\"entity\":{\"external_key\":\"github/timmy3131/design-resource\",\"title\":\"timmy3131/design-resource\",\"subtitle\":\"GitHub repository\",\"main_image_url\":\"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png\",\"avatar_image_url\":\"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png\",\"action\":{\"name\":\"Open in GitHub\",\"url\":\"https://github.com/timmy3131/design-resource\"}},\"updates\":{\"snippets\":[{\"icon\":\"PERSON\",\"message\":\"@Kandychen88 in #4: **我很想领养一只猿**\"}],\"action\":{\"name\":\"View Issue\",\"url\":\"https://github.com/timmy3131/design-resource/issues/4#issuecomment-248221930\"}}}"}],"action":{"name":"View Issue","url":"https://github.com/timmy3131/design-resource/issues/4#issuecomment-248274554"}}}

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/timmy3131/design-resource","title":"timmy3131/design-resource","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/timmy3131/design-resource"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kandychen88 in #4: Hello to whom may concern,\n非常感谢您的善意提醒，赶脚现实生活中无从下手哇。接触不到这类物种但是赶脚他们真的是一个神奇的生物，就是编程啊黑客啊APP哇。你这边有神马建议吗？\n\n\n\n来自 魅族 MX\n\n-------- 原始邮件 --------\n发件人：EastHJ \u003cnotifications@github.com\u003e\n时间：周二 9月20日 19:26\n收件人：timmy3131/design-resource \u003cdesign-resource@noreply.github.com\u003e\n抄送：Kandychen88 \u003c18221430110@163.com\u003e,Comment \u003ccomment@noreply.github.com\u003e\n主题：Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)\n\n\u003e‎想领就领喽,最重要的是行动。想只会留在脑海中 发送自我的 BlackBerry 10 智能手机。 发件人： Kandychen88已发送： 2016年9月20日星期二 15:24收件人： timmy3131/design-resource答复： timmy3131/design-resource主题： Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)我很想领养一只猿\n\u003e\n\u003e—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e\n\u003e\n\u003e\n\u003e\n\u003e\n\u003e\n\u003e\n\u003e\n\u003e{\"api_version\":\"1.0\",\"publisher\":{\"api_key\":\"05dde50f1d1a384dd78767c55493e4bb\",\"name\":\"GitHub\"},\"entity\":{\"external_key\":\"github/timmy3131/design-resource\",\"title\":\"timmy3131/design-resource\",\"subtitle\":\"GitHub repository\",\"main_image_url\":\"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png\",\"avatar_image_url\":\"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png\",\"action\":{\"name\":\"Open in GitHub\",\"url\":\"https://github.com/timmy3131/design-resource\"}},\"updates\":{\"snippets\":[{\"icon\":\"PERSON\",\"message\":\"@Kandychen88 in #4: **我很想领养一只猿**\"}],\"action\":{\"name\":\"View Issue\",\"url\":\"https://github.com/timmy3131/design-resource/issues/4#issuecomment-248221930\"}}} \n\u003e\n\u003e—\n\u003eYou are receiving this because you commented.\n\u003eReply to this email directly, view it on GitHub, or mute the thread.￼\n\u003e\n\u003e{\"api_version\":\"1.0\",\"publisher\":{\"api_key\":\"05dde50f1d1a384dd78767c55493e4bb\",\"name\":\"GitHub\"},\"entity\":{\"external_key\":\"github/timmy3131/design-resource\",\"title\":\"timmy3131/design-resource\",\"subtitle\":\"GitHub repository\",\"main_image_url\":\"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png\",\"avatar_image_url\":\"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png\",\"action\":{\"name\":\"Open in GitHub\",\"url\":\"https://github.com/timmy3131/design-resource\"}},\"updates\":{\"snippets\":[{\"icon\":\"PERSON\",\"message\":\"@EastHJ in #4: ‎想领就领喽,最重要的是行动。想只会留在脑海中 发送自我的 BlackBerry 10 智能手机。 发件人： Kandychen88已发送： 2016年9月20日星期二 15:24收件人： timmy3131/design-resource答复： timmy3131/design-resource主题： Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)我很想领养一只猿\n\n—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.\n\n\n \n \n\n\n\n\n{\\"api_version\\":\\"1.0\\",\\"publisher\\":{\\"api_key\\":\\"05dde50f1d1a384dd78767c55493e4bb\\",\\"name\\":\\"GitHub\\"},\\"entity\\":{\\"external_key\\":\\"github/timmy3131/design-resource\\",\\"title\\":\\"timmy3131/design-resource\\",\\"subtitle\\":\\"GitHub repository\\",\\"main_image_url\\":\\"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png\\\",\\\"avatar_image_url\\\":\\\"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png\\\",\\\"action\\\":{\\\"name\\\":\\\"Open in GitHub\\",\\"url\\":\\"https://github.com/timmy3131/design-resource\\\"}},\\\"updates\\\":{\\\"snippets\\\":[{\\\"icon\\\":\\\"PERSON\\\",\\\"message\\\":\\\"@Kandychen88 in #4: **我很想领养一只猿**\\"}],\\"action\\":{\\"name\\":\\"View Issue\\",\\"url\\":\\"https://github.com/timmy3131/design-resource/issues/4#issuecomment-248221930\\\"}}}\"}],\"action\":{\"name\":\"View Issue\",\"url\":\"https://github.com/timmy3131/design-resource/issues/4#issuecomment-248274554\"}}}"}],"action":{"name":"View Issue","url":"https://github.com/timmy3131/design-resource/issues/4#issuecomment-248293105"}}}

**Comment by EastHJ** [comment]
```
                                                                                  钓鱼么？听着就有意思,哈哈！                                                                                                                                                                                                                                                                                                                                        发送自我的 BlackBerry 10 智能手机。                                                                                                                                                                                                                发件人： 克里斯汀娜已发送： 2016年9月20日星期二 20:17收件人： timmy3131/design-resource答复： timmy3131/design-resource抄送： EastHJ; Comment主题： Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)不惜开小号，你也要来凑热闹。等男人上钩吗？-.-  @Kandychen88 
```

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/timmy3131/design-resource","title":"timmy3131/design-resource","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/timmy3131/design-resource"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kiris-tingna in #4: 不惜开小号，你也要来凑热闹。等男人上钩吗？-.-  @Kandychen88 "}],"action":{"name":"View Issue","url":"https://github.com/timmy3131/design-resource/issues/4#issuecomment-248284266"}}}

**Comment by EastHJ** [comment]
```
                                                                                  ‎大体知道你在哪了,你那里机会满多的呦！                                                                                                                                                                                                                                                                                                                                        发送自我的 BlackBerry 10 智能手机。
```

**Comment by xuecat** [comment]
楼上的，都快一个月了。我的天，还能聊呀！！！！
歇歇脚！！写代码吧！！！！
话说这个咋个才能去掉关注呀！！！咋个每次有人跟帖都给我发邮件！！！晕哦！！！！

**Comment by Kandychen88** [comment]
所以说“猿份”嘛还得看，时间地点际遇等因素都有可能导致不同的结果。如果都对的上，对的人对的时间对的刚刚好，猿类的工作属性都可以都OK吧，那么多猿不都要成家立业的嘛。帮助猿类让世界变得更好。

来自 魅族 MX

-------- 原始邮件 --------
发件人：EastHJ notifications@github.com
时间：周二 9月20日 21:45
收件人：timmy3131/design-resource design-resource@noreply.github.com
抄送：Kandychen88 18221430110@163.com,Mention mention@noreply.github.com
主题：Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)

**Comment by EastHJ** [comment]
‎看来你是很喜欢猿了,‎发送自我的 BlackBerry 10 智能手机。

**Comment by CodeIdeal** [comment]
@xuecat 
![](http://ww4.sinaimg.cn/large/a7eb544fgw1f80xvchiq3j20wl0b877d.jpg)

**Comment by Kandychen88** [comment]
你黑了我的邮箱嘛亲

来自 魅族 MX

-------- 原始邮件 --------
发件人：EastHJ notifications@github.com
时间：周二 9月20日 21:48
收件人：timmy3131/design-resource design-resource@noreply.github.com
抄送：Kandychen88 18221430110@163.com,Mention mention@noreply.github.com
主题：Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)

**Comment by Jack-Siling** [comment]
#知乎观光团到此一游

**Comment by htnosakura** [comment]
知乎观光团到此一游

**Comment by Jackwwz** [comment]
还是你会玩啊，哈哈

**Comment by ma3252788** [comment]
你们都好会玩

2016-11-29 

马春杰 



发件人：Jack <notifications@github.com>
发送时间：2016-11-29 10:08
主题：Re: [timmy3131/design-resource] 妹子你还缺男朋友吗？ (#4)
收件人："timmy3131/design-resource"<design-resource@noreply.github.com>
抄送："arvin"<tianbing010@126.com>,"Comment"<comment@noreply.github.com>

还是你会玩啊，哈哈

**Comment by eddy5885** [comment]
求领养

**Comment by glzcc** [comment]
666

**Comment by RyanyiNF** [comment]
所以这个Issues官方到底还是给个回应先啊

**Comment by seanliCN** [comment]
我帝日天到此一游

**Comment by donnol** [comment]
issue还没关，是不是说明妹子还没找到男票？

**Comment by daggerjames** [comment]
closed??? !!!

**Comment by htnosakura** [comment]
哈哈男朋友关的吗 我第一时间就收到邮件了

**Comment by LUKKACHING** [comment]
我每天就是在GitHub这里看我喜欢的人啥时候工作的，可惜他不喜欢我，还有他不知道这个事哈哈

**Comment by wangchencom** [comment]
WOW
